name: Build image and push

on:
  push:
    branches: [ "jasaz-cli-binary" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} jasaz/my-demo-image:${{ github.sha }}

    - name: Push to Registry
      run: echo "docker push jasaz/my-demo-image:${{ github.sha }}"

    - name: Check if secret is empty
      run: |
        if [ -z "${{ secrets.AQUA_REGISTRY_USER }}" ]; then
          echo "AQUA_REGISTRY_USER is empty!"
          exit 1
        else
          echo "AQUA_REGISTRY_USER is set."
        fi
        if [ -z "${{ secrets.AQUA_REGISTRY_PASSWORD }}" ]; then
          echo "AQUA_REGISTRY_PASSWORD is empty!"
          exit 1
        else
          echo "AQUA_REGISTRY_PASSWORD is set."
        fi

    - name: Download CLI
      run: |
        wget --user ${{ secrets.AQUA_REGISTRY_USER }} --password ${{ secrets.AQUA_REGISTRY_PASSWORD }} https://download.aquasec.com/scanner/2508.10.27/scannercli
        chmod +x scannercli
        
    - name: Scan image
      run: ./scannercli scan -A ${{ secrets.DART_WP_SCANNER_TOKEN }} -H https://d081714cd9-d.cloud.aquasec.com --local jasaz/my-demo-image:${{ github.sha }} --registry jasaz
      continue-on-error: true
